settings:
  commit_msg: "update: readme.md by recent activity"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+09:00"
    text: "Last Updated: {DATE}"
    format: "`dddd. mmmm dS, yyyy, h:MM:ss TT"
  line_prefix: "- "
  disabled_events: [star]

messages:
  comments: "Comment : {ID} in {REPO}"
  push: "Push : commit(s) to {REPO}"
  issue_opened: "Open : issue {ID} in {REPO}"
  issue_closed: "Close : issue {ID} in {REPO}"
  pr_opened: "Open : PR {ID} in {REPO}"
  pr_closed: "Close : PR {ID} in {REPO}"
  pr_merged: "Merge : PR {ID} in {REPO}"
  create_repo: "Create : new repository {REPO}"
  fork_repo: "Fork : {FORK} from {REPO}"
  wiki_create: "Create : new wiki page {WIKI} in {REPO}"
  added_member: "Became collaborator : {REPO}"
  changes_approved: "Approve : {ID} in {REPO}"
  changes_requested: "Request changes : {ID} in {REPO}"
  new_release: "Release : {ID} in {REPO}"
  new_star: "Star : {REPO}"
