settings:
  commit_msg: "update: readme.md by recent activity"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+09:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  line_prefix: "- "
  disabled_events: [star]

messages:
  comments: "`[{DATE}]` Comment : {ID} in {REPO}"
  push: "`[{DATE}]` Push : commits in {REPO}"
  issue_opened: "`[{DATE}]` Open : issue {ID} in {REPO}"
  issue_closed: "`[{DATE}]` Close : issue {ID} in {REPO}"
  pr_opened: "[{DATE}]` Open : PR {ID} in {REPO}"
  pr_closed: "[{DATE}]` Close : PR {ID} in {REPO}"
  pr_merged: "[{DATE}]` Merge : PR {ID} in {REPO}"
  create_repo: "[{DATE}]` Create : new repository {REPO}"
  fork_repo: "[{DATE}]` Fork : {FORK} from {REPO}"
  wiki_create: "[{DATE}]` Create : new wiki page {WIKI} in {REPO}"
  added_member: "[{DATE}]` Became collaborator : {REPO}"
  changes_approved: "[{DATE}]` Approve : {ID} in {REPO}"
  changes_requested: "[{DATE}]` Request changes : {ID} in {REPO}"
  new_release: "[{DATE}]` Release {ID} in {REPO}"
  new_star: "[{DATE}]` Star {REPO}"
